### ISSUE TITLE
Fatal exception within EIO Adapter eio_poll handler

### ISSUE THREAD

**Issue by lucasnetau** [reactphp/filesystem#55]
Within the Adapter.php closure defined in function executeDelayedCall 

```
function ($data, $result, $req) use ($deferred, $errorResultCode, $function, $args) {
            if ($result == $errorResultCode) {
-->                $exception = new UnexpectedValueException(@eio_get_last_error($req));
                $exception->setArgs($args);
                $deferred->reject($exception);
                return;
            }
```

I get the following fatal exception on occasion.

```
Line: 401
Message: Class 'React\Filesystem\Eio\UnexpectedValueException' not found
Trace:
#0 [internal function]: React\Filesystem\Eio\Adapter->React\Filesystem\Eio\{closure}(NULL, -1, Resource id #42794)
#1 /var/www/html/vendor/react/filesystem/src/Eio/Adapter.php(448): eio_poll()
#2 /var/www/html/vendor/react/event-loop/src/ExtEvLoop.php(95): React\Filesystem\Eio\Adapter->handleEvent(Resource id #83)
#3 [internal function]: React\EventLoop\ExtEvLoop->React\EventLoop\{closure}()
#4 /var/www/html/vendor/react/event-loop/src/ExtEvLoop.php(207): EvLoop->run(2)
#5 /var/www/html/event_engine/import_engine.php(143): React\EventLoop\ExtEvLoop->run()
#6 {main}
```

I do not have a way of reproducing this expect running the script for a long time.

**Comment by lucasnetau** [comment]
Sorry, invalid, seems to be an opcache error.
